### ISSUE TITLE
remove this obsolete app from apps.nextcloud.com please

### ISSUE THREAD

**Issue by p-bo** [burgha/nextcloud_uploaddetails#10]
Hello,
would it be possible to follow instructions on:

https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app

and remove your past app:

https://apps.nextcloud.com/apps/uploaddetails

and help through this to tidy up the Nextcloud App store (most importantly it clutters apps catalogue in every Nextcloud instance) a bit please?

Thanks and have a nice day

**Comment by burgha** [comment]
Hello,
Thanks for the Reminder.
As the App is no longer useful in current versions of Nectcloud i deleted it from the App Store
