### ISSUE TITLE
Not showing on NextCloud 16.0.4

### ISSUE THREAD

**Issue by jfha73** [burgha/nextcloud_uploaddetails#2]
Hello,

I just enabled this App on my NextCloud 16.0.4 and uploaded something to see how it looks, but it did not show me anything different than the usual.

Is there anything that needs to be done for it to work?

Thanks.

**Comment by burgha** [comment]
Hi,
The App should work right out of the box, could you try deleting your browser cache and see if it helps ?

**Comment by Excel1** [comment]
Maybe related to this ticket/issue ? 

https://github.com/burgha/nextcloud_uploaddetails/issues/3

**Comment by burgha** [comment]
I'm closing the issue as you did not comment for 2 weeks. if you still have the issue fell free to repoen it
