### ISSUE TITLE
Upload Details not shown

### ISSUE THREAD

**Issue by son1c** [burgha/nextcloud_uploaddetails#6]
The Upload Details are not shown in Safari 13.0.2

Nextcloud Version: 17.0.0

**Comment by joekerna** [comment]
Same here
Nextcloud 17.0.0
Firefox 69.0.2

**Comment by jfha73** [comment]
Same thing on NextCloud 16.0.5, using Google Chrome browser as browser.

**Comment by chenyxr** [comment]
The Upload Details are not shown in Safari  and IE    
Nextcloud Version: 17.0.0

**Comment by aaronjlawson** [comment]
Is this issue still occuring or were there any updates?

**Comment by Skip75** [comment]
I think @burgha doesn't support that application anymore.

**Comment by burgha** [comment]
@Skip75 Yes, the app is currently redundant and no longer needed. I worked with the nextcloud team and as of Nextcloud 18 this app is integrated into core. Sorry for the confusion, i havent come around to updating the readme yet
